// 按时间由近到远
export const data_1 = [
  {
    name: 'EmployeePerformanceService.java',
    quantity: 0,
    uuid: 'd9e9b065-1f5b-4acd-96f5-6ce5cc36e06c',
    childInfos: [
      {
        name: 'query()',
        quantity: 0,
        uuid: '43792145-4f41-46a6-8c67-5fe01e963d37',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: '28c2cd76-40be-4911-a31a-ee05a60005dd',
            childInfos: null,
            committer: null,
            changeRelation: 'CHANGE',
            begin: 0.11831,
            height: 0.038961,
            description: 'changeIf',
          },
          {
            name: null,
            quantity: 0,
            uuid: '28c2cd76-40be-4911-a31a-ee05a60005dd',
            childInfos: null,
            committer: null,
            changeRelation: 'CHANGE',
            begin: 0.18831,
            height: 0.038961,
            description: 'changeVariableDeclaration',
          },
          {
            name: null,
            quantity: 0,
            uuid: '28c2cd76-40be-4911-a31a-ee05a60005dd',
            childInfos: null,
            committer: null,
            changeRelation: 'CHANGE',
            begin: 0.5831,
            height: 0.1961,
            description: 'changeFor',
          },
        ],
        committer: null,
        changeRelation: 'CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
  {
    name: 'BaseScanTask.java',
    quantity: 0,
    uuid: 'f39566de-424b-4993-b0d9-63eb79e29450',
    childInfos: [
      {
        name: 'scan(ScanOperation, String, String, String)',
        quantity: 0,
        uuid: '0f80d245-989b-4224-9e95-85453b4e9b60',
        childInfos: [],
        committer: null,
        changeRelation: 'SELF_CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getAllAggregationCommitCount(String, String)',
        quantity: 0,
        uuid: 'd8e4a9e4-c46e-4bbe-b6c9-4e7b6779b0b6',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: '1c933f70-87a5-48a7-a762-0e5532459906',
            childInfos: null,
            committer: null,
            changeRelation: 'DELETE',
            begin: 0.909091,
            height: 0.045455,
            description: 'deleteReturn',
          },
        ],
        committer: null,
        changeRelation: 'SELF_CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
  {
    name: 'IssueType.java',
    quantity: 0,
    uuid: '18b67027-db29-4950-90ac-84b3b190df91',
    childInfos: [
      {
        name: 'getLanguage()',
        quantity: 0,
        uuid: 'de638946-6ee7-4b47-b27d-6d0032a79985',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: 'b7ec7691-e3ce-4711-a345-7db87a55935f',
            childInfos: null,
            committer: null,
            changeRelation: 'ADD',
            begin: 0.333333,
            height: 0.333333,
            description: null,
          },
        ],
        committer: null,
        changeRelation: 'ADD',
        begin: 0,
        height: 0,
        description: null,
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
  {
    name: 'RecentAllStrategy.java',
    quantity: 0,
    uuid: '071cee11-a409-4d82-995a-0d0a24b5a286',
    childInfos: [
      {
        name: 'filter(Map, List)',
        quantity: 0,
        uuid: 'c36fd753-7ba5-4d00-bc52-d2ce62880855',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: '1335e37d-5905-408e-bc6c-23b06d3f0e0b',
            childInfos: null,
            committer: null,
            changeRelation: 'ADD',
            begin: 0.159091,
            height: 0.068182,
            description: 'addIf',
          },
        ],
        committer: null,
        changeRelation: 'SELF_CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getBaseCommitId(String, String, String)',
        quantity: 0,
        uuid: '3ac645a1-446a-49fa-bfbe-7480d5be2856',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: 'b6c1235f-549f-412d-82d8-f9b7290aede1',
            childInfos: null,
            committer: null,
            changeRelation: 'DELETE',
            begin: 0.221154,
            height: 0.009615,
            description: 'deleteReturn',
          },
          {
            name: null,
            quantity: 0,
            uuid: '702d30ff-cbd9-43b5-8fc7-7a4b46c2f692',
            childInfos: null,
            committer: null,
            changeRelation: 'ADD',
            begin: 0.638889,
            height: 0.027778,
            description: 'addIf',
          },
        ],
        committer: null,
        changeRelation: 'SELF_CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
  {
    name: 'RestInterfaceManager.java',
    quantity: 0,
    uuid: '91f48b69-ec48-4707-a485-e0787048f337',
    childInfos: [
      {
        name: 'freeRepoPath(String, String)',
        quantity: 0,
        uuid: '68302657-06dc-406a-a6d1-f0c3b023f8a2',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: 'e9ad9f16-86bf-47fd-9f8b-15d2d75e54d5',
            childInfos: null,
            committer: null,
            changeRelation: 'DELETE',
            begin: 2,
            height: 0.5,
            description: 'deleteIf',
          },
          {
            name: null,
            quantity: 0,
            uuid: '737acdfe-dd4b-497b-900f-a7d4b465f121',
            childInfos: null,
            committer: null,
            changeRelation: 'DELETE',
            begin: 2.5,
            height: 0.166667,
            description: 'deleteReturn',
          },
          {
            name: null,
            quantity: 0,
            uuid: '4f0f03c0-ea8c-4683-a70f-62c297322a7c',
            childInfos: null,
            committer: null,
            changeRelation: 'ADD',
            begin: 0.043478,
            height: 0.043478,
            description: 'addVariableDeclaration',
          },
        ],
        committer: null,
        changeRelation: 'CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getCommitsOfRepo(String, Integer, Integer)',
        quantity: 0,
        uuid: '5b762125-0ec7-48c6-8f79-677760c5cd30',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: 'fc2d1575-16e5-4d74-a3e9-a38432fed61b',
            childInfos: null,
            committer: null,
            changeRelation: 'DELETE',
            begin: 0.8,
            height: 0.066667,
            description: 'deleteVariableDeclaration',
          },
          {
            name: null,
            quantity: 0,
            uuid: '9a2336cd-ac83-4284-b74c-6d98fc8ede65',
            childInfos: null,
            committer: null,
            changeRelation: 'DELETE',
            begin: 0.866667,
            height: 0.666667,
            description: 'deleteIf',
          },
          {
            name: null,
            quantity: 0,
            uuid: 'b268ecaf-c1fd-4b43-aa6e-a0f69aec6647',
            childInfos: null,
            committer: null,
            changeRelation: 'DELETE',
            begin: 1.6,
            height: 0.066667,
            description: 'deleteReturn',
          },
          {
            name: null,
            quantity: 0,
            uuid: 'fa0d60d1-490d-4560-83bd-8c83a403e3a3',
            childInfos: null,
            committer: null,
            changeRelation: 'ADD',
            begin: 0.054054,
            height: 0.027027,
            description: 'addVariableDeclaration',
          },
          {
            name: null,
            quantity: 0,
            uuid: '694b1357-78d1-4f8b-a52c-ec977275afe6',
            childInfos: null,
            committer: null,
            changeRelation: 'ADD',
            begin: 0.108108,
            height: 0.756757,
            description: 'addWhile',
          },
          {
            name: null,
            quantity: 0,
            uuid: '70fcdc81-3e7f-4b61-a816-3ba9c2f3c027',
            childInfos: null,
            committer: null,
            changeRelation: 'ADD',
            begin: 0.945946,
            height: 0.027027,
            description: 'addReturn',
          },
        ],
        committer: null,
        changeRelation: 'CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getCommitsOfRepoByConditions(String, Integer, Integer, Boolean)',
        quantity: 0,
        uuid: '23ce75ae-fbd3-44a0-b207-da3e71bc0c39',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: '93271177-030f-49ae-8adc-78096161a9c9',
            childInfos: null,
            committer: null,
            changeRelation: 'DELETE',
            begin: 0.65,
            height: 0.05,
            description: 'deleteVariableDeclaration',
          },
          {
            name: null,
            quantity: 0,
            uuid: 'f58c67e4-7633-450b-9c21-8e2906572b72',
            childInfos: null,
            committer: null,
            changeRelation: 'DELETE',
            begin: 0.7,
            height: 0.5,
            description: 'deleteIf',
          },
          {
            name: null,
            quantity: 0,
            uuid: '7dd15c5d-92f8-4b62-8967-8cd86551f2cc',
            childInfos: null,
            committer: null,
            changeRelation: 'DELETE',
            begin: 1.25,
            height: 0.15,
            description: 'deleteIf',
          },
          {
            name: null,
            quantity: 0,
            uuid: '3b6dc3bb-0bf1-40fd-88c4-38af36d9e9b8',
            childInfos: null,
            committer: null,
            changeRelation: 'DELETE',
            begin: 1.4,
            height: 0.05,
            description: 'deleteReturn',
          },
          {
            name: null,
            quantity: 0,
            uuid: 'a3f2c7c0-59da-4e19-88c9-efd0420a1ad1',
            childInfos: null,
            committer: null,
            changeRelation: 'ADD',
            begin: 0.05,
            height: 0.025,
            description: 'addVariableDeclaration',
          },
          {
            name: null,
            quantity: 0,
            uuid: '034a7b9b-9405-48ad-a762-b60392da462c',
            childInfos: null,
            committer: null,
            changeRelation: 'ADD',
            begin: 0.075,
            height: 0.025,
            description: 'addVariableDeclaration',
          },
          {
            name: null,
            quantity: 0,
            uuid: '53d30324-7929-4db9-8bcb-36e0721b1516',
            childInfos: null,
            committer: null,
            changeRelation: 'ADD',
            begin: 0.1,
            height: 0.8,
            description: 'addWhile',
          },
          {
            name: null,
            quantity: 0,
            uuid: '7a700d84-a41d-4d24-a83f-ca0b03621564',
            childInfos: null,
            committer: null,
            changeRelation: 'ADD',
            begin: 0.925,
            height: 0.025,
            description: 'addReturn',
          },
        ],
        committer: null,
        changeRelation: 'CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getRepoById(String)',
        quantity: 0,
        uuid: 'b10fc381-9725-46dc-a25c-1192c93c0ca5',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: '9ca0ab16-8284-4560-b23c-f210fe6374dc',
            childInfos: null,
            committer: null,
            changeRelation: 'DELETE',
            begin: 4,
            height: 0.1333333,
            description: 'deleteReturn',
          },
          {
            name: null,
            quantity: 0,
            uuid: '11967976-ca27-4bc0-af8b-8af3f10333de',
            childInfos: null,
            committer: null,
            changeRelation: 'ADD',
            begin: 0.136364,
            height: 0.045455,
            description: 'addVariableDeclaration',
          },
          {
            name: null,
            quantity: 0,
            uuid: '2c63fb58-5d20-42f9-ab68-2e000e037d56',
            childInfos: null,
            committer: null,
            changeRelation: 'ADD',
            begin: 0.181818,
            height: 0.727273,
            description: 'addWhile',
          },
          {
            name: null,
            quantity: 0,
            uuid: 'e3b71f94-da37-430a-9a61-d2bdd0e46715',
            childInfos: null,
            committer: null,
            changeRelation: 'ADD',
            begin: 0.909091,
            height: 0.045455,
            description: 'addReturn',
          },
        ],
        committer: null,
        changeRelation: 'CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getRepoPath(String, String)',
        quantity: 0,
        uuid: '861baa9f-5912-4632-8627-bcb54ecb7e16',
        childInfos: [],
        committer: null,
        changeRelation: 'CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
  {
    name: 'ScanServiceImpl.java',
    quantity: 0,
    uuid: '42d84382-fb9e-4dc2-80d8-13a65799937a',
    childInfos: [
      {
        name: 'getLatestScanFailedCommitIdAndDeveloper(String, String, String)',
        quantity: 0,
        uuid: 'a68a2c44-f375-4e14-a5c9-a863c78575f8',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: 'b24eb789-4770-4f9a-be3e-3289e2d8f1f7',
            childInfos: null,
            committer: null,
            changeRelation: 'DELETE',
            begin: 0.6875,
            height: 0.0625,
            description: 'deleteReturn',
          },
        ],
        committer: null,
        changeRelation: 'SELF_CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getPreScannedCommitByCurrentCommit(String, String, String)',
        quantity: 0,
        uuid: 'd2aa2dac-8bbb-40de-bd76-15ac53dccc98',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: '1126dac6-882f-4f4a-806b-284462ad5c08',
            childInfos: null,
            committer: null,
            changeRelation: 'ADD',
            begin: 0.217391,
            height: 0.130435,
            description: 'addIf',
          },
          {
            name: null,
            quantity: 0,
            uuid: 'e57f21d6-cfaf-46fd-aff1-5f0ad986221e',
            childInfos: null,
            committer: null,
            changeRelation: 'DELETE',
            begin: 0.55,
            height: 0.05,
            description: 'deleteReturn',
          },
        ],
        committer: null,
        changeRelation: 'SELF_CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
];

// 5月28日
export const data_2 = [
  {
    name: 'EmployeePerformanceService.java',
    quantity: 0,
    uuid: 'd9e9b065-1f5b-4acd-96f5-6ce5cc36e06c',
    childInfos: [
      {
        name: 'query()',
        quantity: 0,
        uuid: '43792145-4f41-46a6-8c67-5fe01e963d37',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: '28c2cd76-40be-4911-a31a-ee05a60005dd',
            childInfos: null,
            committer: null,
            changeRelation: 'DELETE',
            begin: 0.12831,
            height: 0.28961,
            description: 'deleteSwitch',
          },
          {
            name: null,
            quantity: 0,
            uuid: '28c2cd76-40be-4911-a31a-ee05a60005dd',
            childInfos: null,
            committer: null,
            changeRelation: 'CHANGE',
            begin: 0.6831,
            height: 0.058961,
            description: 'changeIf',
          },
        ],
        committer: null,
        changeRelation: 'CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
  {
    name: 'BaseScanTask.java',
    quantity: 0,
    uuid: 'f39566de-424b-4993-b0d9-63eb79e29450',
    childInfos: [
      {
        name: 'scan(ScanOperation, String, String, String)',
        quantity: 0,
        uuid: '0f80d245-989b-4224-9e95-85453b4e9b60',
        childInfos: [],
        committer: null,
        changeRelation: 'SELF_CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getAllAggregationCommitCount(String, String)',
        quantity: 0,
        uuid: 'd8e4a9e4-c46e-4bbe-b6c9-4e7b6779b0b6',
        childInfos: [],
        committer: null,
        changeRelation: null,
        begin: 0,
        height: 0,
        description: null,
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
  {
    name: 'IssueType.java',
    quantity: 0,
    uuid: '18b67027-db29-4950-90ac-84b3b190df91',
    childInfos: [
      {
        name: 'getLanguage()',
        quantity: 0,
        uuid: 'de638946-6ee7-4b47-b27d-6d0032a79985',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: 'b7ec7691-e3ce-4711-a345-7db87a55935f',
            childInfos: null,
            committer: null,
            changeRelation: 'CHANGE',
            begin: 0.133333,
            height: 0.333333,
            description: 'changeIf',
          },
        ],
        committer: null,
        changeRelation: 'CHANGE',
        begin: 0,
        height: 0,
        description: 'changeFor',
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
  {
    name: 'RecentAllStrategy.java',
    quantity: 0,
    uuid: '071cee11-a409-4d82-995a-0d0a24b5a286',
    childInfos: [
      {
        name: 'filter(Map, List)',
        quantity: 0,
        uuid: 'c36fd753-7ba5-4d00-bc52-d2ce62880855',
        childInfos: [],
        committer: null,
        changeRelation: 'SELF_CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getBaseCommitId(String, String, String)',
        quantity: 0,
        uuid: '3ac645a1-446a-49fa-bfbe-7480d5be2856',
        childInfos: [],
        committer: null,
        changeRelation: null,
        begin: 0,
        height: 0,
        description: null,
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
  {
    name: 'RestInterfaceManager.java',
    quantity: 0,
    uuid: '91f48b69-ec48-4707-a485-e0787048f337',
    childInfos: [
      {
        name: 'freeRepoPath(String, String)',
        quantity: 0,
        uuid: '68302657-06dc-406a-a6d1-f0c3b023f8a2',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: '737acdfe-dd4b-497b-900f-a7d4b465f121',
            childInfos: null,
            committer: null,
            changeRelation: 'DELETE',
            begin: 0.8,
            height: 0.0466667,
            description: 'deleteReturn',
          },
          {
            name: null,
            quantity: 0,
            uuid: '4f0f03c0-ea8c-4683-a70f-62c297322a7c',
            childInfos: null,
            committer: null,
            changeRelation: 'CHANGE',
            begin: 0.043478,
            height: 0.043478,
            description: 'changeVariableDeclaration',
          },
        ],
        committer: null,
        changeRelation: 'CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getCommitsOfRepo(String, Integer, Integer)',
        quantity: 0,
        uuid: '5b762125-0ec7-48c6-8f79-677760c5cd30',
        childInfos: [],
        committer: null,
        changeRelation: null,
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getCommitsOfRepoByConditions(String, Integer, Integer, Boolean)',
        quantity: 0,
        uuid: '23ce75ae-fbd3-44a0-b207-da3e71bc0c39',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: 'f58c67e4-7633-450b-9c21-8e2906572b72',
            childInfos: null,
            committer: null,
            changeRelation: 'CHANGE',
            begin: 0.2,
            height: 0.1,
            description: 'changeIf',
          },
          {
            name: null,
            quantity: 0,
            uuid: '7dd15c5d-92f8-4b62-8967-8cd86551f2cc',
            childInfos: null,
            committer: null,
            changeRelation: 'CHANGE',
            begin: 0.35,
            height: 0.15,
            description: 'changeIf',
          },
          {
            name: null,
            quantity: 0,
            uuid: '3b6dc3bb-0bf1-40fd-88c4-38af36d9e9b8',
            childInfos: null,
            committer: null,
            changeRelation: 'DELETE',
            begin: 1.4,
            height: 0.05,
            description: 'deleteReturn',
          },
          {
            name: null,
            quantity: 0,
            uuid: 'a3f2c7c0-59da-4e19-88c9-efd0420a1ad1',
            childInfos: null,
            committer: null,
            changeRelation: 'ADD',
            begin: 0.01,
            height: 0.025,
            description: 'addVariableDeclaration',
          },
          {
            name: null,
            quantity: 0,
            uuid: '034a7b9b-9405-48ad-a762-b60392da462c',
            childInfos: null,
            committer: null,
            changeRelation: 'CHANGE',
            begin: 0.075,
            height: 0.025,
            description: 'changeVariableDeclaration',
          },
          {
            name: null,
            quantity: 0,
            uuid: '53d30324-7929-4db9-8bcb-36e0721b1516',
            childInfos: null,
            committer: null,
            changeRelation: 'change',
            begin: 0.1,
            height: 0.8,
            description: 'changeWhile',
          },
        ],
        committer: null,
        changeRelation: 'CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getRepoById(String)',
        quantity: 0,
        uuid: 'b10fc381-9725-46dc-a25c-1192c93c0ca5',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: '338e76df-d7c8-43d6-b366-381019dade9c',
            childInfos: null,
            committer: null,
            changeRelation: 'CHANGE',
            begin: 0.090909,
            height: 0.045455,
            description: 'changeVariableDeclaration',
          },
          {
            name: null,
            quantity: 0,
            uuid: '2c63fb58-5d20-42f9-ab68-2e000e037d56',
            childInfos: null,
            committer: null,
            changeRelation: 'ADD',
            begin: 0.281818,
            height: 0.127273,
            description: 'addIf',
          },
        ],
        committer: null,
        changeRelation: 'CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getRepoPath(String, String)',
        quantity: 0,
        uuid: '861baa9f-5912-4632-8627-bcb54ecb7e16',
        childInfos: [],
        committer: null,
        changeRelation: null,
        begin: 0,
        height: 0,
        description: null,
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
  {
    name: 'ScanServiceImpl.java',
    quantity: 0,
    uuid: '42d84382-fb9e-4dc2-80d8-13a65799937a',
    childInfos: [
      {
        name: 'getLatestScanFailedCommitIdAndDeveloper(String, String, String)',
        quantity: 0,
        uuid: 'a68a2c44-f375-4e14-a5c9-a863c78575f8',
        childInfos: [],
        committer: null,
        changeRelation: 'SELF_CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getPreScannedCommitByCurrentCommit(String, String, String)',
        quantity: 0,
        uuid: 'd2aa2dac-8bbb-40de-bd76-15ac53dccc98',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: 'e57f21d6-cfaf-46fd-aff1-5f0ad986221e',
            childInfos: null,
            committer: null,
            changeRelation: 'DELETE',
            begin: 0.95,
            height: 0.05,
            description: 'deleteReturn',
          },
        ],
        committer: null,
        changeRelation: 'CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
];

//5月27日
export const data_3 = [
  {
    name: 'EmployeePerformanceService.java',
    quantity: 0,
    uuid: 'd9e9b065-1f5b-4acd-96f5-6ce5cc36e06c',
    childInfos: [
      {
        name: 'query()',
        quantity: 0,
        uuid: '43792145-4f41-46a6-8c67-5fe01e963d37',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: '28c2cd76-40be-4911-a31a-ee05a60005dd',
            childInfos: null,
            committer: null,
            changeRelation: 'DELETE',
            begin: 0.22831,
            height: 0.03961,
            description: 'deleteBreak',
          },
          {
            name: null,
            quantity: 0,
            uuid: '28c2cd76-40be-4911-a31a-ee05a60005dd',
            childInfos: null,
            committer: null,
            changeRelation: 'CHANGE',
            begin: 0.4831,
            height: 0.038961,
            description: 'changeIf',
          },
        ],
        committer: null,
        changeRelation: 'CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
  {
    name: 'BaseScanTask.java',
    quantity: 0,
    uuid: 'f39566de-424b-4993-b0d9-63eb79e29450',
    childInfos: [
      {
        name: 'scan(ScanOperation, String, String, String)',
        quantity: 0,
        uuid: '0f80d245-989b-4224-9e95-85453b4e9b60',
        childInfos: [],
        committer: null,
        changeRelation: null,
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getAllAggregationCommitCount(String, String)',
        quantity: 0,
        uuid: 'd8e4a9e4-c46e-4bbe-b6c9-4e7b6779b0b6',
        childInfos: [],
        committer: null,
        changeRelation: 'SELF_CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
  {
    name: 'IssueType.java',
    quantity: 0,
    uuid: '18b67027-db29-4950-90ac-84b3b190df91',
    childInfos: [
      {
        name: 'getLanguage()',
        quantity: 0,
        uuid: 'de638946-6ee7-4b47-b27d-6d0032a79985',
        childInfos: [],
        committer: null,
        changeRelation: null,
        begin: 0,
        height: 0,
        description: 'changeFor',
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
  {
    name: 'RecentAllStrategy.java',
    quantity: 0,
    uuid: '071cee11-a409-4d82-995a-0d0a24b5a286',
    childInfos: [
      {
        name: 'filter(Map, List)',
        quantity: 0,
        uuid: 'c36fd753-7ba5-4d00-bc52-d2ce62880855',
        childInfos: [],
        committer: null,
        changeRelation: null,
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getBaseCommitId(String, String, String)',
        quantity: 0,
        uuid: '3ac645a1-446a-49fa-bfbe-7480d5be2856',
        childInfos: [],
        committer: null,
        changeRelation: null,
        begin: 0,
        height: 0,
        description: null,
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
  {
    name: 'RestInterfaceManager.java',
    quantity: 0,
    uuid: '91f48b69-ec48-4707-a485-e0787048f337',
    childInfos: [
      {
        name: 'freeRepoPath(String, String)',
        quantity: 0,
        uuid: '68302657-06dc-406a-a6d1-f0c3b023f8a2',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: '737acdfe-dd4b-497b-900f-a7d4b465f121',
            childInfos: null,
            committer: null,
            changeRelation: 'DELETE',
            begin: 0.8,
            height: 0.0466667,
            description: 'deleteReturn',
          },
          {
            name: null,
            quantity: 0,
            uuid: '4f0f03c0-ea8c-4683-a70f-62c297322a7c',
            childInfos: null,
            committer: null,
            changeRelation: 'CHANGE',
            begin: 0.043478,
            height: 0.043478,
            description: 'changeVariableDeclaration',
          },
        ],
        committer: null,
        changeRelation: 'CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getCommitsOfRepo(String, Integer, Integer)',
        quantity: 0,
        uuid: '5b762125-0ec7-48c6-8f79-677760c5cd30',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: '737acdfe-dd4b-497b-900f-a7d4b465f121',
            childInfos: null,
            committer: null,
            changeRelation: 'DELETE',
            begin: 0.09,
            height: 0.0466667,
            description: 'deleteReturn',
          },
        ],
        committer: null,
        changeRelation: 'CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getCommitsOfRepoByConditions(String, Integer, Integer, Boolean)',
        quantity: 0,
        uuid: '23ce75ae-fbd3-44a0-b207-da3e71bc0c39',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: 'f58c67e4-7633-450b-9c21-8e2906572b72',
            childInfos: null,
            committer: null,
            changeRelation: 'CHANGE',
            begin: 0.21,
            height: 0.2,
            description: 'changeIf',
          },
          {
            name: null,
            quantity: 0,
            uuid: '7dd15c5d-92f8-4b62-8967-8cd86551f2cc',
            childInfos: null,
            committer: null,
            changeRelation: 'CHANGE',
            begin: 0.75,
            height: 0.15,
            description: 'changeWhile',
          },
          {
            name: null,
            quantity: 0,
            uuid: '034a7b9b-9405-48ad-a762-b60392da462c',
            childInfos: null,
            committer: null,
            changeRelation: 'CHANGE',
            begin: 0.075,
            height: 0.025,
            description: 'changeVariableDeclaration',
          },
        ],
        committer: null,
        changeRelation: 'CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getRepoById(String)',
        quantity: 0,
        uuid: 'b10fc381-9725-46dc-a25c-1192c93c0ca5',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: '9ca0ab16-8284-4560-b23c-f210fe6374dc',
            childInfos: null,
            committer: null,
            changeRelation: 'ADD',
            begin: 0.1,
            height: 0.033333,
            description: 'addVariableDeclaration',
          },
          {
            name: null,
            quantity: 0,
            uuid: '2c63fb58-5d20-42f9-ab68-2e000e037d56',
            childInfos: null,
            committer: null,
            changeRelation: 'CHANGE',
            begin: 0.281818,
            height: 0.127273,
            description: 'changeIf',
          },
        ],
        committer: null,
        changeRelation: 'CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getRepoPath(String, String)',
        quantity: 0,
        uuid: '861baa9f-5912-4632-8627-bcb54ecb7e16',
        childInfos: [],
        committer: null,
        changeRelation: null,
        begin: 0,
        height: 0,
        description: null,
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
  {
    name: 'ScanServiceImpl.java',
    quantity: 0,
    uuid: '42d84382-fb9e-4dc2-80d8-13a65799937a',
    childInfos: [
      {
        name: 'getLatestScanFailedCommitIdAndDeveloper(String, String, String)',
        quantity: 0,
        uuid: 'a68a2c44-f375-4e14-a5c9-a863c78575f8',
        childInfos: [],
        committer: null,
        changeRelation: null,
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getPreScannedCommitByCurrentCommit(String, String, String)',
        quantity: 0,
        uuid: 'd2aa2dac-8bbb-40de-bd76-15ac53dccc98',
        childInfos: [],
        committer: null,
        changeRelation: 'SELF_CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
    ],
    committer: null,
    changeRelation: null,
    begin: 0,
    height: 0,
    description: null,
  },
];

//5月23日
export const data_4 = [
  {
    name: 'EmployeePerformanceService.java',
    quantity: 0,
    uuid: 'd9e9b065-1f5b-4acd-96f5-6ce5cc36e06c',
    childInfos: [
      {
        name: 'query()',
        quantity: 0,
        uuid: '43792145-4f41-46a6-8c67-5fe01e963d37',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: '28c2cd76-40be-4911-a31a-ee05a60005dd',
            childInfos: null,
            committer: null,
            changeRelation: 'CHANGE',
            begin: 0.02831,
            height: 0.13961,
            description: 'changeFor',
          },
          {
            name: null,
            quantity: 0,
            uuid: '28c2cd76-40be-4911-a31a-ee05a60005dd',
            childInfos: null,
            committer: null,
            changeRelation: 'CHANGE',
            begin: 0.4831,
            height: 0.038961,
            description: 'changeIf',
          },
          {
            name: null,
            quantity: 0,
            uuid: '28c2cd76-40be-4911-a31a-ee05a60005dd',
            childInfos: null,
            committer: null,
            changeRelation: 'CHANGE',
            begin: 0.9831,
            height: 0.038961,
            description: '',
          },
        ],
        committer: null,
        changeRelation: 'CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
  {
    name: 'BaseScanTask.java',
    quantity: 0,
    uuid: 'f39566de-424b-4993-b0d9-63eb79e29450',
    childInfos: [
      {
        name: 'scan(ScanOperation, String, String, String)',
        quantity: 0,
        uuid: '0f80d245-989b-4224-9e95-85453b4e9b60',
        childInfos: [],
        committer: null,
        changeRelation: 'SELF_CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getAllAggregationCommitCount(String, String)',
        quantity: 0,
        uuid: 'd8e4a9e4-c46e-4bbe-b6c9-4e7b6779b0b6',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: '1c933f70-87a5-48a7-a762-0e5532459906',
            childInfos: null,
            committer: null,
            changeRelation: 'DELETE',
            begin: 0.909091,
            height: 0.045455,
            description: 'deleteReturn',
          },
        ],
        committer: null,
        changeRelation: 'SELF_CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
  {
    name: 'IssueType.java',
    quantity: 0,
    uuid: '18b67027-db29-4950-90ac-84b3b190df91',
    childInfos: [
      {
        name: 'getLanguage()',
        quantity: 0,
        uuid: 'de638946-6ee7-4b47-b27d-6d0032a79985',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: 'b7ec7691-e3ce-4711-a345-7db87a55935f',
            childInfos: null,
            committer: null,
            changeRelation: 'DELETE',
            begin: 0.333333,
            height: 0.0333333,
            description: 'deleteIf',
          },
        ],
        committer: null,
        changeRelation: 'CHANGE',
        begin: 0.42,
        height: 0.21,
        description: 'changeFor',
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
  {
    name: 'RecentAllStrategy.java',
    quantity: 0,
    uuid: '071cee11-a409-4d82-995a-0d0a24b5a286',
    childInfos: [
      {
        name: 'filter(Map, List)',
        quantity: 0,
        uuid: 'c36fd753-7ba5-4d00-bc52-d2ce62880855',
        childInfos: [],
        committer: null,
        changeRelation: null,
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getBaseCommitId(String, String, String)',
        quantity: 0,
        uuid: '3ac645a1-446a-49fa-bfbe-7480d5be2856',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: 'b6c1235f-549f-412d-82d8-f9b7290aede1',
            childInfos: null,
            committer: null,
            changeRelation: 'DELETE',
            begin: 0.221154,
            height: 0.009615,
            description: 'deleteReturn',
          },
          {
            name: null,
            quantity: 0,
            uuid: '702d30ff-cbd9-43b5-8fc7-7a4b46c2f692',
            childInfos: null,
            committer: null,
            changeRelation: 'ADD',
            begin: 0.638889,
            height: 0.027778,
            description: 'addIf',
          },
        ],
        committer: null,
        changeRelation: 'SELF_CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
  {
    name: 'RestInterfaceManager.java',
    quantity: 0,
    uuid: '91f48b69-ec48-4707-a485-e0787048f337',
    childInfos: [
      {
        name: 'freeRepoPath(String, String)',
        quantity: 0,
        uuid: '68302657-06dc-406a-a6d1-f0c3b023f8a2',
        childInfos: [],
        committer: null,
        changeRelation: null,
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getCommitsOfRepo(String, Integer, Integer)',
        quantity: 0,
        uuid: '5b762125-0ec7-48c6-8f79-677760c5cd30',
        childInfos: [],
        committer: null,
        changeRelation: 'CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getCommitsOfRepoByConditions(String, Integer, Integer, Boolean)',
        quantity: 0,
        uuid: '23ce75ae-fbd3-44a0-b207-da3e71bc0c39',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: '737acdfe-dd4b-497b-900f-a7d4b465f121',
            childInfos: null,
            committer: null,
            changeRelation: 'DELETE',
            begin: 0.8,
            height: 0.0466667,
            description: 'deleteReturn',
          },
          {
            name: null,
            quantity: 0,
            uuid: '4f0f03c0-ea8c-4683-a70f-62c297322a7c',
            childInfos: null,
            committer: null,
            changeRelation: 'CHANGE',
            begin: 0.043478,
            height: 0.043478,
            description: 'changeVariableDeclaration',
          },
        ],
        committer: null,
        changeRelation: 'CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getRepoById(String)',
        quantity: 0,
        uuid: 'b10fc381-9725-46dc-a25c-1192c93c0ca5',
        childInfos: [],
        committer: null,
        changeRelation: null,
        begin: 0,
        height: 0,
        description: null,
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
  {
    name: 'ScanServiceImpl.java',
    quantity: 0,
    uuid: '42d84382-fb9e-4dc2-80d8-13a65799937a',
    childInfos: [
      {
        name: 'getLatestScanFailedCommitIdAndDeveloper(String, String, String)',
        quantity: 0,
        uuid: 'a68a2c44-f375-4e14-a5c9-a863c78575f8',
        childInfos: [],
        committer: null,
        changeRelation: null,
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getPreScannedCommitByCurrentCommit(String, String, String)',
        quantity: 0,
        uuid: 'd2aa2dac-8bbb-40de-bd76-15ac53dccc98',
        childInfos: [],
        committer: null,
        changeRelation: null,
        begin: 0,
        height: 0,
        description: null,
      },
    ],
    committer: null,
    changeRelation: null,
    begin: 0,
    height: 0,
    description: null,
  },
];

//5月22日
export const data_5 = [
  {
    name: 'EmployeePerformanceService.java',
    quantity: 0,
    uuid: 'd9e9b065-1f5b-4acd-96f5-6ce5cc36e06c',
    childInfos: [
      {
        name: 'query()',
        quantity: 0,
        uuid: '43792145-4f41-46a6-8c67-5fe01e963d37',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: '28c2cd76-40be-4911-a31a-ee05a60005dd',
            childInfos: null,
            committer: null,
            changeRelation: 'DELETE',
            begin: 0.01831,
            height: 0.058961,
            description: 'deleteIf',
          },
          {
            name: null,
            quantity: 0,
            uuid: '28c2cd76-40be-4911-a31a-ee05a60005dd',
            childInfos: null,
            committer: null,
            changeRelation: 'ADD',
            begin: 0.078831,
            height: 0.278961,
            description: 'addSwitch',
          },
        ],
        committer: null,
        changeRelation: 'CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
  {
    name: 'BaseScanTask.java',
    quantity: 0,
    uuid: 'f39566de-424b-4993-b0d9-63eb79e29450',
    childInfos: [
      {
        name: 'scan(ScanOperation, String, String, String)',
        quantity: 0,
        uuid: '0f80d245-989b-4224-9e95-85453b4e9b60',
        childInfos: [],
        committer: null,
        changeRelation: null,
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getAllAggregationCommitCount(String, String)',
        quantity: 0,
        uuid: 'd8e4a9e4-c46e-4bbe-b6c9-4e7b6779b0b6',
        childInfos: [],
        committer: null,
        changeRelation: 'SELF_CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
  {
    name: 'IssueType.java',
    quantity: 0,
    uuid: '18b67027-db29-4950-90ac-84b3b190df91',
    childInfos: [
      {
        name: 'getLanguage()',
        quantity: 0,
        uuid: 'de638946-6ee7-4b47-b27d-6d0032a79985',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: 'b7ec7691-e3ce-4711-a345-7db87a55935f',
            childInfos: null,
            committer: null,
            changeRelation: 'ADD',
            begin: 0.433333,
            height: 0.0333333,
            description: 'addIf',
          },
        ],
        committer: null,
        changeRelation: 'CHANGE',
        begin: 0.42,
        height: 0.21,
        description: 'changeFor',
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
  {
    name: 'RecentAllStrategy.java',
    quantity: 0,
    uuid: '071cee11-a409-4d82-995a-0d0a24b5a286',
    childInfos: [
      {
        name: 'filter(Map, List)',
        quantity: 0,
        uuid: 'c36fd753-7ba5-4d00-bc52-d2ce62880855',
        childInfos: [],
        committer: null,
        changeRelation: null,
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getBaseCommitId(String, String, String)',
        quantity: 0,
        uuid: '3ac645a1-446a-49fa-bfbe-7480d5be2856',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: 'b6c1235f-549f-412d-82d8-f9b7290aede1',
            childInfos: null,
            committer: null,
            changeRelation: 'CHANGE',
            begin: 0.221154,
            height: 0.209615,
            description: 'changeFor',
          },
        ],
        committer: null,
        changeRelation: 'CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
  {
    name: 'RestInterfaceManager.java',
    quantity: 0,
    uuid: '91f48b69-ec48-4707-a485-e0787048f337',
    childInfos: [
      {
        name: 'freeRepoPath(String, String)',
        quantity: 0,
        uuid: '68302657-06dc-406a-a6d1-f0c3b023f8a2',
        childInfos: [],
        committer: null,
        changeRelation: null,
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getCommitsOfRepo(String, Integer, Integer)',
        quantity: 0,
        uuid: '5b762125-0ec7-48c6-8f79-677760c5cd30',
        childInfos: [
          {
            name: null,
            quantity: 0,
            uuid: '9ca0ab16-8284-4560-b23c-f210fe6374dc',
            childInfos: null,
            committer: null,
            changeRelation: 'ADD',
            begin: 0.1,
            height: 0.033333,
            description: 'addVariableDeclaration',
          },
          {
            name: null,
            quantity: 0,
            uuid: '2c63fb58-5d20-42f9-ab68-2e000e037d56',
            childInfos: null,
            committer: null,
            changeRelation: 'CHANGE',
            begin: 0.281818,
            height: 0.127273,
            description: 'changeIf',
          },
        ],
        committer: null,
        changeRelation: 'CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getCommitsOfRepoByConditions(String, Integer, Integer, Boolean)',
        quantity: 0,
        uuid: '23ce75ae-fbd3-44a0-b207-da3e71bc0c39',
        childInfos: [],
        committer: null,
        changeRelation: 'SELF_CHANGE',
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getRepoById(String)',
        quantity: 0,
        uuid: 'b10fc381-9725-46dc-a25c-1192c93c0ca5',
        childInfos: [],
        committer: null,
        changeRelation: null,
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getRepoPath(String, String)',
        quantity: 0,
        uuid: '861baa9f-5912-4632-8627-bcb54ecb7e16',
        childInfos: [],
        committer: null,
        changeRelation: null,
        begin: 0,
        height: 0,
        description: null,
      },
    ],
    committer: null,
    changeRelation: 'CHANGE',
    begin: 0,
    height: 0,
    description: null,
  },
  {
    name: 'ScanServiceImpl.java',
    quantity: 0,
    uuid: '42d84382-fb9e-4dc2-80d8-13a65799937a',
    childInfos: [
      {
        name: 'getLatestScanFailedCommitIdAndDeveloper(String, String, String)',
        quantity: 0,
        uuid: 'a68a2c44-f375-4e14-a5c9-a863c78575f8',
        childInfos: [],
        committer: null,
        changeRelation: null,
        begin: 0,
        height: 0,
        description: null,
      },
      {
        name: 'getPreScannedCommitByCurrentCommit(String, String, String)',
        quantity: 0,
        uuid: 'd2aa2dac-8bbb-40de-bd76-15ac53dccc98',
        childInfos: [],
        committer: null,
        changeRelation: null,
        begin: 0,
        height: 0,
        description: null,
      },
    ],
    committer: null,
    changeRelation: null,
    begin: 0,
    height: 0,
    description: null,
  },
];

export const commits = [
  {
    commitId: '1',
    commitTime: 'June 08',
    parent1: 'May 28',
  },
  {
    commitId: '2',
    commitTime: 'May 28',
    parent1: 'May 27',
  },
  {
    commitId: '3',
    commitTime: 'May 27',
    parent1: 'May 23',
  },
  {
    commitId: '4',
    commitTime: 'May 23',
    parent1: 'May 22',
  },
  {
    commitId: '5',
    commitTime: 'May 22',
    parent1: '6',
    // parent2: "7"
    // },{
    //     commitId: "6",
    //     commitTime: "May 22",
    //     parent1: "8"
    // },{
    //     commitId: "7",
    //     commitTime: "May 22",
    //     parent1: "9"
    // },{
    //     commitId: "8",
    //     commitTime: "May 22",
    //     parent1: "10"
    // },{
    //     commitId: "9",
    //     commitTime: "May 22",
    //     parent1: "10"
    // },{
    //     commitId: "10",
    //     commitTime: "May 22",
    //     parent1: "11"
  },
];

export const message_1 = {
  developer_name: 'jfstylejf',
  commit_time: '2020-06-08 17:40:25',
  commit_message: 'add Swagger2 component for API doc',
};

export const message_2 = {
  developer_name: 'linwangzai',
  commit_time: '2020-05-28 19:21:32',
  commit_message: 'add filter developer',
};

export const message_3 = {
  developer_name: 'jfstylejf',
  commit_time: '2020-05-27 20:20:25',
  commit_message: 'fix inner API bug',
};

export const message_4 = {
  developer_name: 'jfstylejf',
  commit_time: '2020-05-23 11:30:15',
  commit_message:
    'add tool field to ignore_record table(Some statements still need to be changed)',
};

export const message_5 = {
  developer_name: 'linwangzai',
  commit_time: '2020-05-22 11:02:13',
  commit_message: ' fix mapping failed',
};
